- name: "Discord"
  identifier:
    kind: "exe"
    id: "Discord.exe"
  options:
    - force

- name: "Spotify"
  identifier:
    kind: "exe"
    id: "Spotify.exe"
  options:
    - force

- name: "Steam"
  identifier:
    kind: "exe"
    id: "steam.exe"
  options:
    - force

- name: "Flow.Launcher"
  identifier:
    kind: "exe"
    id: "Flow.Launcher.exe"
  float_identifiers:
    - kind: "exe"
      id: "Flow.Launcher.exe"
